[package]
name = "ilmenite"
version = "0.0.1"
authors = ["Austin Johnson <me@austinj.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = { path = "../vulkano/vulkano" }
vulkano-shaders = { path = "../vulkano/vulkano-shaders" }
allsorts = "0.1.0"
ordered-float = "1.0.2"
parking_lot = "0.10.0"
