[package]
name = "ilmenite"
version = "0.0.1"
authors = ["Austin Johnson <me@austinj.me>"]
repository = "https://github.com/AustinJ235/ilmenite"
documentation = "https://docs.rs/ilmenite"
description = "A rust library for shaping, placing, and rasterizing text primarily for Basalt."
license = "MIT"
readme = "README.md"
keywords = ["vulkan", "text", "shaper", "raster"]
categories = ["graphics","gui","parsing","text-processing"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "56728c565f3ca0f92a842b3d4a80ba5a8b0890dd" }
vulkano-shaders = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "56728c565f3ca0f92a842b3d4a80ba5a8b0890dd" }
allsorts = "0.1.0"
ordered-float = "1.0.2"
parking_lot = "0.10.0"
