[package]
name = "ilmenite"
version = "0.7.0"
authors = ["Austin Johnson <me@austinj.me>"]
repository = "https://github.com/AustinJ235/ilmenite"
documentation = "https://docs.rs/ilmenite"
description = "A rust library for shaping, placing, and rasterizing text primarily for Basalt."
license = "MIT"
readme = "README.md"
keywords = ["vulkan", "text", "shaper", "raster"]
categories = ["graphics","gui","parsing","text-processing"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.27"
vulkano-shaders = "0.27"
allsorts = "0.6.0"
ordered-float = "2.8.0"
parking_lot = "0.11.2"
crossbeam = "0.8.1"
