[package]
name = "examples"
version = "0.0.0"
authors = ["Austin <me@austinj.me>"]
publish = false

[dependencies]
basalt = { path = "../../basalt" }

[patch.'https://github.com/austinj235/ilmenite']
ilmenite = { path = "../" }
